# -*- coding: utf-8 -*-
"""Копия блокнота "test_mts_v1.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151sZIhytDlxQtNzkDOMvU7QC6MupXxBY

Поставлена задача анализа и обработки датасета, содержащего информацию об оттоке клиентов из телекома. Необходимо разработать модель, способную с высокой точностью прогнозировать отток клиентов
"""

!pip install catboost
!pip install ydata-profiling

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, classification_report, confusion_matrix,
    roc_curve, auc, precision_recall_curve, average_precision_score
)

from sklearn.dummy import DummyClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from catboost import CatBoostClassifier
from ydata_profiling import ProfileReport
from google.colab import files
from IPython.display import IFrame

"""Нужно построить модель, предсказывающую отток, оценить качество этой модели и гипотетические перспективы использования этой модели в реальном бизнес-процессе. Для начала рассмотрим имеющийся датасет"""

df = pd.read_csv(
    "https://raw.githubusercontent.com/sonofastronaut/test_mts/main/telco-customer-churn.csv"
)

profile = ProfileReport(df)
profile.to_file("report.html")
files.download("report.html")

# пропуски
missing = df.isna().mean().sort_values(ascending=False)
print("\nДоля пропусков по колонкам:\n", missing)

# дубликаты
duplicates_count = df.duplicated().sum()
print("\nКоличество дубликатов:", duplicates_count)

"""Откроем и проанализируем датасет. Размер сета 20468 строк на 29 столбцов, среди столбцов есть категориальные значения, которые необходимо предобработать. Так же отдельно отмечу, что в датасете полностью отсутствуют пропуски, дубликаты или ячейки со значением NULL, что исключает необходимость в обработке числовых значений. Однако, при рассмотрении датасета видно, что в нем есть столбец noadditionallines, в котором все значения равны \N, что говорит о неинформативности данного столбца, покажу ниже"""

# \N-значения
null_counts = {}
for column in df.columns:
    # Считаем точные совпадения с '\N'
    count = (df[column] == '\\N').sum()
    if count > 0:
        null_counts[column] = count

# Вывод результатов
print(f"Всего столбцов: {len(df.columns)}")
print(f"Столбцов с значением '\\N': {len(null_counts)}")
print("\nРаспределение значений '\\N' по столбцам:")
if null_counts:
    for col, count in null_counts.items():
        percentage = (count / len(df)) * 100
        print(f"  {col}: {count} строк ({percentage:.2f}%)")
else:
    print("  Значения '\\N' не найдены")

"""Учитывая отсутствие хоть какой-то информативности в этом столбце, считаю, что его стоит исключить из датасета

Так же перед кодированием категориальных столбцов, я рассмотрю количество уникальных значений в каждой колонке
"""

# Вывод количества уникальных значений в каждой колонке
cat_cols = df.select_dtypes(include=['object']).columns

print("Уникальные значения в категориальных столбцах:")
print("=" * 50)

for col in cat_cols:
    unique_count = df[col].nunique()
    print(f"\n{col}:")
    print(f"  Уникальных значений: {unique_count}")

"""Внимание стоит обратить на столбец state, в котором есть 50 уникальных значений, что при OHE даст нам 50 новых столбцов, тогда как в самом датасете их 29. Решение об удалении этого столбца я приму после построения матрицы корреляций

Далее рассмотрим, как распределена целевая переменная
"""

# распределение целевой переменной

plt.figure(figsize=(6, 4))
sns.countplot(x="churn", data=df)
plt.title("Распределение целевой переменной churn")
plt.xlabel("Churn")
plt.ylabel("Количество")
plt.show()

print("\nДоли классов:")
print(df["churn"].value_counts(normalize=True))

"""В распределении целевой переменной виден явный дисбаланс, но стоит отметить, что в телекоме такое распределение можно назвать ожидаемым, потому что люди довольно редко меняют оператора связи. При дальнейшей обработке данного датасета я должен учесть этот дисбаланс"""

# Корреляции числовых признаков

df_corr = df.copy()
df_corr["churn"] = df_corr["churn"].astype(int)

num_cols_corr = df_corr.select_dtypes(include=[np.number])

plt.figure(figsize=(10, 6))
sns.heatmap(
    num_cols_corr.corr(),
    cmap="Reds",
    center=0,
    linewidths=0.5
)
plt.title("Матрица корреляций числовых признаков")

plt.show()

target_corr = (
    num_cols_corr
        .corr()["churn"]
        .drop("churn")
        .abs()
        .sort_values(ascending=False)
)

target_corr

"""Судя по полученному хитмапу, фича year не имеет корреляции как таковой, посмотрим количество уникальных значений"""

print(f"year: \nУникальных значений: {df['year'].nunique()}")

"""В колонке year всего лишь одно уникальное значение 2015, неинформативно, предсказательной нагрузки не несет, можем удалять

Далее рассмотрим корреляцию категориальных признаков с целевой переменной. Предварительно удалим столбец noadditionallines, т.к. его нецелесообразно обрабатывать
"""

df.drop(columns=["noadditionallines"], inplace=True)

import scipy.stats as ss

def cramers_v(x, y):
    confusion_matrix = pd.crosstab(x, y)
    chi2 = ss.chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(r, k) - 1)))

cat_cols = df.select_dtypes(include='object').columns

cramers_matrix = pd.DataFrame(
    np.zeros((len(cat_cols), len(cat_cols))),
    index=cat_cols,
    columns=cat_cols
)

for col1 in cat_cols:
    for col2 in cat_cols:
        cramers_matrix.loc[col1, col2] = cramers_v(df[col1], df[col2])

plt.figure(figsize=(12, 10))
sns.heatmap(
    cramers_matrix,
    cmap="Reds",
    linewidths=0.5
)
plt.title("Корреляция категориальных признаков")
plt.show()

cat_target_corr = {}

for col in cat_cols:
    cat_target_corr[col] = cramers_v(df[col], df["churn"])

cat_target_corr = (
    pd.Series(cat_target_corr)
    .sort_values(ascending=False)
)

cat_target_corr

"""Проанализируем матрицы корреляций. Из них становится очевидно, что сильных линейных связей между фичами и целевой переменной нет. Но тем не менее, мы можем отбросить:
 - callingnum - номер телефона, уникальный идентификатор без предсказательной силы
 - customerid - уникальный идентификатор пользователя, предсказательной силы также не имеет
 - year - год сбора информации, никакой предсказательной силы в нем нет, удалим его
 - noadditionallines - фича, содержащая в себе только "\N", удаляем

  Отдельно отмечу, что ранее упомянутая фича state имеет самую значительную корреляцию с целевой переменной среди всех категориальных переменных, соответственно, удалять её нецелесообразно
  
  Удалим перечисленные фичи
"""

df = df.drop(columns=['callingnum', 'customerid','year'])
df.shape

"""Далее произведем подготовку данных, разобьем на трейн и тест

"""

# Подготовка данных

X = df.drop(columns=["churn"])
y = df["churn"].astype(int)

categorical_features_for_pipeline = X.select_dtypes(include=['object']).columns
numerical_features_for_pipeline = X.select_dtypes(include=[np.number]).columns


X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

"""Используем следующие модели: dummy для построения baseline, решающее дерево, рандом форест и градиентный бустинг"""

preprocessor_ohe = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', numerical_features_for_pipeline),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False),
         categorical_features_for_pipeline)
    ]
)

X_train_ohe = preprocessor_ohe.fit_transform(X_train)
X_test_ohe = preprocessor_ohe.transform(X_test)

models = {
    "dummy": DummyClassifier(strategy="most_frequent"),
    "decision_tree": DecisionTreeClassifier(max_depth=6, random_state=42),
    "random_forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "gradient_boosting": GradientBoostingClassifier(random_state=42)
}

for name, model in models.items():
    model.fit(X_train_ohe, y_train)
    probs = model.predict_proba(X_test_ohe)[:, 1]
    print(name, roc_auc_score(y_test, probs))

#  Обучение и оценка моделей

roc_auc_scores = {}
roc_curves = {}
pr_auc_scores = {}

for name, model in models.items():
    # обучение
    model.fit(X_train_ohe, y_train)

    # предсказания
    preds = model.predict(X_test_ohe)
    probs = model.predict_proba(X_test_ohe)[:, 1]

    # метрики
    roc_auc = roc_auc_score(y_test, probs)
    roc_auc_scores[name] = roc_auc

    fpr, tpr, _ = roc_curve(y_test, probs)
    roc_curves[name] = (fpr, tpr)

    pr_auc_scores[name] = average_precision_score(y_test, probs)

    print("=" * 60)
    print(name.upper())
    print("=" * 60)
    print(f"Accuracy:  {accuracy_score(y_test, preds):.4f}")
    print(f"Precision: {precision_score(y_test, preds, zero_division=0):.4f}")
    print(f"Recall:    {recall_score(y_test, preds, zero_division=0):.4f}")
    print(f"F1-score:  {f1_score(y_test, preds, zero_division=0):.4f}")
    print(f"ROC-AUC:   {roc_auc:.4f}")
    print("\nConfusion matrix:\n", confusion_matrix(y_test, preds))
    print("\nClassification report:\n", classification_report(y_test, preds, zero_division=0))

"""Так же попробуем обучить CatBoost и проанализировать его работу в сравнении с моделями, для которых проводилась предподготовка категориальных столбцов"""

X_train_cb = X_train.copy()
X_test_cb = X_test.copy()

cat_features_idx = [
    X_train_cb.columns.get_loc(col)
    for col in categorical_features_for_pipeline
]

catboost_model = CatBoostClassifier(
    iterations=300,
    learning_rate=0.05,
    depth=6,
    random_state=42,
    verbose=False
)

catboost_model.fit(
    X_train_cb,
    y_train,
    cat_features=cat_features_idx
)

preds_cb = catboost_model.predict(X_test_cb)
probs_cb = catboost_model.predict_proba(X_test_cb)[:, 1]
print("\n  CatBoost \n")

print(f"Accuracy:  {accuracy_score(y_test, preds_cb):.4f}")
print(f"Precision: {precision_score(y_test, preds_cb, zero_division=0):.4f}")
print(f"Recall:    {recall_score(y_test, preds_cb, zero_division=0):.4f}")
print(f"F1-score:  {f1_score(y_test, preds_cb, zero_division=0):.4f}")
print(f"ROC-AUC:   {roc_auc_score(y_test, probs_cb):.4f}")
print("\nConfusion matrix:\n", confusion_matrix(y_test, preds_cb))
print("\nClassification report:\n", classification_report(y_test, preds, zero_division=0))

"""Модели обучены. По отчетам уже можем сделать вывод о том, что лучше всего в этом наборе моделей отработал рандом форест, показав самый лучший f1 и recall. Неидеально, но лучше, чем остальные модели. Построим ROC-AUC кривые для обученных моделей."""

# ROC-AUC кривые

plt.figure(figsize=(8, 6))

# sklearn модели
for name, (fpr, tpr) in roc_curves.items():
    plt.plot(
        fpr,
        tpr,
        label=f"{name} (AUC = {roc_auc_scores[name]:.3f})"
    )

# catboost
probs_cb = catboost_model.predict_proba(X_test_cb)[:, 1]
fpr_cb, tpr_cb, _ = roc_curve(y_test, probs_cb)
roc_auc_cb = roc_auc_score(y_test, probs_cb)
plt.plot(
    fpr_cb,
    tpr_cb,
    label=f"catboost (AUC = {roc_auc_cb:.3f})"
)

plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC-AUC кривые для всех моделей")
plt.legend(loc="lower right")
plt.grid(True)
plt.show()

"""Графики ROC-AUC уже наглядно показывают нам, что лучше всего в этом наборе моделей отработал именно рандом форест."""

# PR для CatBoost (native categoricals)
probs_cb = catboost_model.predict_proba(X_test_cb)[:, 1]
precision_cb, recall_cb, _ = precision_recall_curve(y_test, probs_cb)
ap_cb = average_precision_score(y_test, probs_cb)

plt.figure(figsize=(8, 6))

# sklearn модели
for name, model in models.items():
    model.fit(X_train_ohe, y_train)
    probs = model.predict_proba(X_test_ohe)[:, 1]

    precision, recall, _ = precision_recall_curve(y_test, probs)
    ap = average_precision_score(y_test, probs)

    plt.plot(recall, precision, label=f"{name} (AP = {ap:.3f})")

# catboost отдельно
plt.plot(recall_cb, precision_cb, label=f"catboost (AP = {ap_cb:.3f})")

plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision–Recall curves")
plt.legend()
plt.grid(True)
plt.show()

"""На графике precision-recall так же видно, что лучшее соотношение показывает именно рандом форест, тогда как остальные модели практически не определяют отток.

Какой вывод можно сделать из проделанного исследования: из обученных моделей мы получили то, что без работы с гиперпараметрами и балансировкой классов лучше всего с предсказанием оттока справляется рандом форест. В дальнейшем при внедрении этой модели в бизнес-процессы можно увеличить процент предсказываемого оттока. Так же хочу отметить, что можно дополнительно поработать с бустингом, например, использовать LightGBM или XGBoost, их результаты явно можно приблизить к результатам рандом фореста
"""